"""Update blog and user relationship

Revision ID: 182d68c6bf0e
Revises: 7feb7afecaee
Create Date: 2023-04-10 21:50:44.209078

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "182d68c6bf0e"
down_revision = "7feb7afecaee"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("blog_user_id_fkey", "blog", type_="foreignkey")
    op.drop_column("blog", "user_id")
    op.add_column("user", sa.Column("blog_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "user", "blog", ["blog_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="foreignkey")
    op.drop_column("user", "blog_id")
    op.add_column(
        "blog", sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_foreign_key("blog_user_id_fkey", "blog", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###
