"""Add user birthday column

Revision ID: 7feb7afecaee
Revises: 746603f9e369
Create Date: 2023-04-10 17:14:33.520188

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7feb7afecaee"
down_revision = "746603f9e369"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("birthday", sa.Date(), nullable=True))
    op.alter_column(
        "user", "name", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.drop_column("user", "age")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("age", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.alter_column("user", "name", existing_type=sa.VARCHAR(length=100), nullable=True)
    op.drop_column("user", "birthday")
    # ### end Alembic commands ###
