name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install packages
        run: |
          pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run unit tests
        run: |
          export PYTHONPATH=$(pwd)
          poetry run pytest -s -v --cov=animal_massage --cov-report term tests
